name: release

on:
  push:
    branches:
      - "main"

jobs:
  release:
    uses: signoz/primus.workflows/.github/workflows/js-release.yaml@js-release
    secrets: inherit
    with:
      PRIMUS_REF: git
